services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${APP_NAME}_app
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - APP_NAME=${APP_NAME}
      - APP_ENV=${APP_ENV}
      - APP_KEY=${APP_KEY}
      - APP_DEBUG=${APP_DEBUG}
      - APP_SECRET=${APP_SECRET}
      - APP_URL=${APP_URL}
      - DATABASE_URL=pgsql://${DB_USERNAME}:${DB_PASSWORD}@db:${DB_PORT}/${DB_DATABASE}
      - SESSION_DRIVER=${SESSION_DRIVER}
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: nginx_web
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: postgres:15-alpine
    container_name: db
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  dbdata:
