name: Symfony CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Récupération du code
        uses: actions/checkout@v3

      - name: Installation PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: none

      - name: Installation des dépendances
        run: composer install --prefer-dist --no-progress

      - name: Lancer les tests PHPUnit
        run: |
            php bin/console doctrine:database:create --env=test
            php bin/console doctrine:migrations:migrate --env=test --no-interaction
            APP_ENV=test ./vendor/bin/phpunit --testdox
