name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Build de l'image Docker
    - name: Build Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

    # Créer un .env minimal dans le workspace pour Symfony
    - name: Create minimal .env
      run: |
        echo "APP_ENV=test" > .env
        echo "APP_DEBUG=1" >> .env
        echo "DATABASE_URL=sqlite:///%kernel.project_dir%/data/database.sqlite" >> .env
        echo "MESSENGER_TRANSPORT_DSN=doctrine://default?auto_setup=0" >> .env
        echo "MAILER_DSN='null://null'" >> .env

    # Installer les dépendances PHP via composer
    - name: Install dependencies
      run: composer install --no-ansi --no-interaction --no-scripts --no-progress

    # Préparer la base SQLite
    - name: Prepare SQLite DB
      run: |
        mkdir -p data
        touch data/database.sqlite
        php bin/console doctrine:schema:create --env=test

    # Lancer les tests PHPUnit
    - name: Run PHPUnit
      run: vendor/bin/phpunit --testdox
      env:
        APP_ENV: test
        DATABASE_URL: "sqlite:///%kernel.project_dir%/data/database.sqlite"
