name: Symfony CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupérer le code
      - uses: actions/checkout@v4

      # 2. Installer PHP + extensions nécessaires + Composer
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, pdo_sqlite, zip, intl
          tools: composer, symfony-cli

      # 3. Créer un .env.test minimal pour éviter l'erreur Dotenv
      - name: Create .env.test
        run: |
          echo "APP_ENV=test" > .env.test
          echo "DATABASE_URL=sqlite:///%kernel.project_dir%/var/data.db" >> .env.test

      # 4. Installer les dépendances sans scripts automatiques
      - name: Install dependencies
        run: composer install --no-scripts --prefer-dist --no-interaction

      # 5. Créer la base de données test et mettre à jour le schéma
      - name: Prepare test DB
        env:
          APP_ENV: test
          DATABASE_URL: "sqlite:///%kernel.project_dir%/var/data.db"
        run: |
          php bin/console doctrine:database:create --env=test --if-not-exists
          php bin/console doctrine:schema:update --env=test --force

      # 6. Lancer les tests PHPUnit
      - name: Run tests
        env:
          APP_ENV: test
          DATABASE_URL: "sqlite:///%kernel.project_dir%/var/data.db"
        run: |
          php bin/phpunit --testdox
