name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:15
        ports: ["5432:5432"]
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: db_test
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - uses: actions/checkout@v4

    # Build de l'image Docker
    - name: Build Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

    # Créer un .env minimal dans le workspace pour Symfony
    - name: Create minimal .env
      run: |
        echo "APP_ENV=test" > .env
        echo "APP_DEBUG=1" >> .env
        echo "DATABASE_URL=pgsql://postgres:postgres@127.0.0.1:5432/db" >> .env
        echo "MESSENGER_TRANSPORT_DSN=doctrine://default?auto_setup=0" >> .env
        echo "MAILER_DSN=null://null" >> .env

    # Installer les dépendances PHP via composer
    - name: Install dependencies
      run: composer install --no-ansi --no-interaction --no-scripts --no-progress

    # Créer le DatabaseTestTrait avec le bon contenu
    - name: Create DatabaseTestTrait
      run: |
        mkdir -p tests/Traits
        cat > tests/Traits/DatabaseTestTrait.php << 'EOF'
        <?php

        namespace App\Tests\Traits;

        use Doctrine\ORM\EntityManagerInterface;
        use Doctrine\Common\DataFixtures\Purger\ORMPurger;
        use Doctrine\Common\DataFixtures\Executor\ORMExecutor;
        use Doctrine\Common\DataFixtures\Loader;
        use App\DataFixtures\AppFixtures;

        trait DatabaseTestTrait
        {
            protected EntityManagerInterface $em;

            protected function loadDatabaseFixtures(): void
            {
                $this->em = self::getContainer()->get('doctrine')->getManager();

                // Purger la base
                $purger = new ORMPurger($this->em);
                $executor = new ORMExecutor($this->em, $purger);

                $loader = new Loader();
                $loader->addFixture(new AppFixtures());

                $executor->execute($loader->getFixtures());
            }
        }
        EOF
        
    # Préparer la base de données
    - name: Prepare DB
      run: |
        APP_ENV=test php bin/console doctrine:database:create --if-not-exists
        APP_ENV=test php bin/console doctrine:migrations:migrate --no-interaction

    # Lancer les tests PHPUnit
    - name: Run PHPUnit
      run: |
        APP_ENV=test php bin/console doctrine:migrations:migrate --no-interaction
        vendor/bin/phpunit --testdox
      env:
        APP_ENV: test
        DATABASE_URL: "pgsql://postgres:postgres@127.0.0.1:5432/db"
