name: Symfony CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  symfony-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Installer PHP
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      # Installer Composer
      - name: Install Composer dependencies
        run: composer install --no-interaction --no-scripts --no-progress

      # Créer un .env minimal pour les tests
      - name: Create minimal .env
        run: |
          echo "APP_ENV=test" > .env
          echo "APP_DEBUG=1" >> .env
          echo "DATABASE_URL=sqlite:///%kernel.project_dir%/var/data.db" >> .env
          echo "MESSENGER_TRANSPORT_DSN=doctrine://default?auto_setup=0" >> .env
          echo "MAILER_DSN=null://null" >> .env

      # Préparer la base SQLite
      - name: Prepare SQLite DB
        run: |
          mkdir -p var
          touch var/data.db
          php bin/console doctrine:schema:create --env=test

      # Lancer les tests
      - name: Run PHPUnit
        run: vendor/bin/phpunit --testdox
        env:
          APP_ENV: test
          DATABASE_URL: sqlite:///%kernel.project_dir%/var/data.db
