name: Symfony CI Minimal SQLite

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  symfony-tests:
    runs-on: ubuntu-latest

    env:
      APP_ENV: test
      APP_DEBUG: 1
      DATABASE_URL: "sqlite:///%kernel.project_dir%/var/data.db"
      MESSENGER_TRANSPORT_DSN: "doctrine://default?auto_setup=0"
      MAILER_DSN: "null://null"

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          extensions: mbstring, intl, pdo_sqlite, zip

      - name: Install PHP dependencies
        run: composer install --no-interaction --no-scripts --prefer-dist --optimize-autoloader

      - name: Prepare SQLite DB
        run: |
          mkdir -p var
          touch var/data.db
          php bin/console doctrine:schema:create --env=test
          php bin/console doctrine:fixtures:load --no-interaction --env=test

      - name: Run PHPUnit
        run: vendor/bin/phpunit --testdox
