name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:15
        env:
          POSTGRES_DB: symfony_test
          POSTGRES_USER: symfony
          POSTGRES_PASSWORD: symfony
        ports:
          - 5432:5432
        # important : permet à Symfony d'attendre que Postgres soit prêt
        options: >-
          --health-cmd="pg_isready -U symfony"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      # Installe PHP + extensions nécessaires
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: mbstring, pdo_pgsql, zip
          tools: symfony, composer

      # Installe les dépendances
      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      # Prépare la base de données test
      - name: Prepare DB
        run: |
          php bin/console doctrine:database:create --env=test --if-not-exists
          php bin/console doctrine:schema:update --env=test --force

      # Lance les tests
      - name: Run tests
        env:
          APP_ENV: test
          DATABASE_URL: "sqlite:///%kernel.project_dir%/var/data.db"
        run: php bin/phpunit --testdox
