name: Symfony

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  symfony-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4.5'

      - uses: actions/checkout@v4

      # Copier le fichier .env.test si .env.test.local n'existe pas
      - name: Copy .env.test.local
        run: php -r "file_exists('.env.test.local') || copy('.env.test', '.env.test.local');"

      # Cacher le dossier vendor pour accélérer les builds
      - name: Cache Composer packages
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      # Installer les dépendances
      - name: Install Dependencies
        env:
          APP_ENV: test
        run: composer install --no-interaction --prefer-dist

      # Créer la base de données SQLite
      - name: Create SQLite Database
        run: |
          mkdir -p var/data
          touch var/data/database.sqlite

      # Exécuter les tests PHPUnit avec les bonnes variables d'environnement
      - name: Execute tests (Unit and Feature)
        env:
          APP_ENV: test
          DATABASE_URL: "sqlite:///%kernel.project_dir%/var/data/database.sqlite"
          SYMFONY_DEPRECATIONS_HELPER: disabled
        run: vendor/bin/phpunit --testdox
